Feature Engineering:
------------------------------
Feature engineering is the process of converting raw data into meaningful numerical features so that a machine learning model can understand patterns and make better predictions.

1.Feature Exploration:
--------------------------------
The process of analyzing and visualizing features to uncover patterns, distributions, correlations, and potential issues in the dataset before applying machine learning.

2.Feature Creation:
----------------------------
The process of generating new meaningful features from existing data using domain knowledge or mathemaatical operations to help the model learn better patterns.

3.Feature Encoding:
-----------------------------
The process of converting categorical or non-eric features into numeric form so machine learning models can process them effectively.

4.Feature Scaling:(normalization- standard ,minmax scaler)
--------------------------
The process of transforming numerical features to a standard range or distribution so that no feature dominates the learning process due to its scale.

5.Feature Selection:
-----------------------------
The process of identifying and keeping only the most relevant features while removing irrelevant or redundant ones too improve model performance and reduce overfitting.

Feature Creation:(Adds intelligence)
-----------------------------------------------------

# Defintion:

Feature Creation is the process of creating new features from existing data using domain knowledge and mathematical operations to help the model learn better patters.

# why it "Adds Intelligence":

- raw data may not show hiden realtionships.

- new features provide extra information

- model cannot think logically- features guide learning

# Common Types of feature Creation:

- Domain-baesd features(real-world logic)
- mathematical combination(sum, average, ratio)
- interaction features(combined effect of featues)
- Polynomial features(non-linear realtionships)

# Example:

- Total=Math+Science
- efficiency= Total_marks/ Study_hours

# Impact on model:

- imroves accuracy
- helps models capture complex patterns
- makes simple modles performs better

# Feature Creation

In [2]:
import pandas as pd
df=pd.DataFrame({
    "study_hours":[2,4,6,8,10],
    "attendance":[60,70,80,90,95],
    "maths":[40,55,65,75,80],
    "science":[42,58,68,78,88]
})
df

   study_hours  attendance  maths  science
0            2          60     40       42
1            4          70     55       58
2            6          80     65       68
3            8          90     75       78
4           10          95     80       88

# Domain- Based Feature

In [3]:
df["total_marks"]=df["maths"]+df["science"]
df

   study_hours  attendance  maths  science  total_marks
0            2          60     40       42           82
1            4          70     55       58          113
2            6          80     65       68          133
3            8          90     75       78          153
4           10          95     80       88          168

# Mathematical Feature

In [4]:
df["marks_per_hour"]=df["total_marks"] / df["study_hours"]
df

   study_hours  attendance  maths  science  total_marks  marks_per_hour
0            2          60     40       42           82       41.000000
1            4          70     55       58          113       28.250000
2            6          80     65       68          133       22.166667
3            8          90     75       78          153       19.125000
4           10          95     80       88          168       16.800000

# Interaction Feature

In [5]:
df["study_attendance_interaction"]= df["study_hours"] * df["attendance"]
df

,study_hours,attendance,maths,science,total_marks,marks_per_hour,study_attendance_interaction
0,2,60,40,42,82,41.000000,120
1,4,70,55,58,113,28.250000,280
2,6,80,65,68,133,22.166667,480
3,8,90,75,78,153,19.125000,720
4,10,95,80,88,168,16.800000,950

# Polynomial Feature

In [6]:
df["study_hours_squared"]= df["study_hours"] ** 2
df

,study_hours,attendance,maths,science,total_marks,marks_per_hour,study_attendance_interaction,study_hours_squared
0,2,60,40,42,82,41.000000,120,4
1,4,70,55,58,113,28.250000,280,16
2,6,80,65,68,133,22.166667,480,36
3,8,90,75,78,153,19.125000,720,64
4,10,95,80,88,168,16.800000,950,100

 Feature Selection:
 ---------------------------
It is the process of selecting only relevant feeatures and removing irrelevant or redundant ones to improve model performance.

why it "Remove Noise":
-----------------------------------
- Too many features confuse the model 
- Irrelevant features cause overfitting
- Noise reduces prediction accuracy

Types of Feature Selection:
----------------------------------------
- Filter methods(correlation, chi-square)
- Wrapper Methods(forward, backward, RFE)
- Embedded methods(Lasso, three-based models)

Example:
--------------
- removing weakly correlated features
- dropping features with zero importance
- selecting top features using RFE

Impact on model:
-------------------------
- reduces overfitting
- improves generalization
- speeds up training

# Feature selection

In [8]:
df

,study_hours,attendance,maths,science,total_marks,marks_per_hour,study_attendance_interaction,study_hours_squared
0,2,60,40,42,82,41.000000,120,4
1,4,70,55,58,113,28.250000,280,16
2,6,80,65,68,133,22.166667,480,36
3,8,90,75,78,153,19.125000,720,64
4,10,95,80,88,168,16.800000,950,100

In [9]:
x=df.drop("science", axis=1)
y=df["science"]

In [10]:
x

,study_hours,attendance,maths,total_marks,marks_per_hour,study_attendance_interaction,study_hours_squared
0,2,60,40,82,41.000000,120,4
1,4,70,55,113,28.250000,280,16
2,6,80,65,133,22.166667,480,36
3,8,90,75,153,19.125000,720,64
4,10,95,80,168,16.800000,950,100

In [11]:
y

0    42
1    58
2    68
3    78
4    88
Name: science, dtype: int64

# Filter Methods(Statistics- Based)

# correlation Methods:

In [12]:
df.corr()["science"].sort_values(ascending=False)

science                         1.000000
total_marks                     0.998981
maths                           0.995467
study_hours                     0.994309
attendance                      0.994110
study_attendance_interaction    0.983804
study_hours_squared             0.958102
marks_per_hour                 -0.968737
Name: science, dtype: float64

# Selecting important features

In [13]:
corr=df.corr()["science"].abs()
corr

study_hours                     0.994309
attendance                      0.994110
maths                           0.995467
science                         1.000000
total_marks                     0.998981
marks_per_hour                  0.968737
study_attendance_interaction    0.983804
study_hours_squared             0.958102
Name: science, dtype: float64

In [16]:
selected_features= corr[corr>0.8].index
selected_features

Index(['study_hours', 'attendance', 'maths', 'science', 'total_marks',
       'marks_per_hour', 'study_attendance_interaction',
       'study_hours_squared'],
      dtype='object')