# Feature Encoding

Feature encoding is the process of converting a non numerical data into a numerical format that machine learning algorithms can understand and process.

we choose this because:: the type of categorical data, the number of unique values in a categorical column, and the model we plan to train Types of categorical data--> nominal(no order), ordinal(order)

Nominal Data: No order existence ex: red, ordinal data order exists ex: size(small<medium<large) rating(low<medium<High) Importance: text data can't be used directly in model training. proper encoding: Improves model Accuracy Prevents wrong assumptions Make training stable

# Common Feature Encoding Techniques(7)

Label encoding, One hot encoding , Target Encoding, Ordinal Encoding , Frequency Encoding, Binary Encoding, Feature Hashmap

# Label encoding

  Each category is assigned a unique interger( e.g: "red":0,"green":1).
use for ordinal data ( inherent order) or with tree based models that are not sensitive to the numberical order.

In [1]:
import pandas as pd
df=pd.DataFrame({
    "color": ["Red", "Green", "Blue","Green","Red"],
    "Size": ["Small", "medium","Large","medium","Small"],
    "City": ["Hyderabad","Delhi","Mumbai","Delhi","Chennai"],
    "Target": [10,20,15,25,12]
})
df

   color    Size       City  Target
0    Red   Small  Hyderabad      10
1  Green  medium      Delhi      20
2   Blue   Large     Mumbai      15
3  Green  medium      Delhi      25
4    Red   Small    Chennai      12

In [7]:
from sklearn.preprocessing import LalebelEncoder

ImportError: cannot import name 'LalebelEncoder' from 'sklearn.preprocessing' (C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\__init__.py)

In [8]:
df["Color_Label"] =LabelEncoder().fit_transform(df["color"])
df[["color","Color_Label"]]

NameError: name 'LabelEncoder' is not defined

# One- Hot Encoding
      1- present, 0 - absent
      Create a new binary column  for each category, with a 1 indicating the presence of that category and 0 otherwise.
      Ideal for nominal data with low to medium cardinalitym and for linear models and neural networks.

In [9]:
one_hot=pd.get_dummies(df["color"],prefix="color") # if the value is there then it will be true and it will get the prefix as color
one_hot

   color_Blue  color_Green  color_Red
0       False        False       True
1       False         True      False
2        True        False      False
3       False         True      False
4       False        False       True

In [10]:
oh=pd.get_dummies(df,columns=["color"])
oh

     Size       City  Target  color_Blue  color_Green  color_Red
0   Small  Hyderabad      10       False        False       True
1  medium      Delhi      20       False         True      False
2   Large     Mumbai      15        True        False      False
3  medium      Delhi      25       False         True      False
4   Small    Chennai      12       False        False       True

# Ordinal Encoding
   Similar to Label Encoding, but the integer assignment is based on the specific, predefined order or rank of the categories( e.g: "low":0, "medium":1,"high":2).
   Use specifically when the categorical variable has the natural meaning ful order.

In [11]:
from sklearn.preprocessing import OrdinalEncoder # takes the values based on order

In [12]:
order=[["Small","medium","Large"]]

df["Size_ordinal"]=OrdinalEncoder(categories=order).fit_transform(df[["Size"]])
df[["Size","Size_ordinal"]]

     Size  Size_ordinal
0   Small           0.0
1  medium           1.0
2   Large           2.0
3  medium           1.0
4   Small           0.0

# Target Encoding
Each category is replaced with the mean of the target varibale for that category.
Effective for high-cardinality features and when there's a strong relationship between the category and the target variable, but requires careful validation to valide target values

In [13]:
te=df.groupby("City")["Target"].mean()
df["city_Target_Enc"]=df["City"].map(te)
df[["City","city_Target_Enc"]]

        City  city_Target_Enc
0  Hyderabad             10.0
1      Delhi             22.5
2     Mumbai             15.0
3      Delhi             22.5
4    Chennai             12.0

# Frequency Encoding
   Replaces each category with its frequency(count) in the dataset. 
   Useful when the frequencey of a category is predictive of the target variable.

In [14]:
fe=df.groupby("City")["Target"].count()
df["city_Target_Enc"]=df["City"].map(fe)  #method 1
df[["City","city_Target_Enc"]]

        City  city_Target_Enc
0  Hyderabad                1
1      Delhi                2
2     Mumbai                1
3      Delhi                2
4    Chennai                1

In [15]:
f=df["City"].value_counts()
df["city_Target_Enc"]=df["City"].map(fe) # method 2
df[["City","city_Target_Enc"]]

        City  city_Target_Enc
0  Hyderabad                1
1      Delhi                2
2     Mumbai                1
3      Delhi                2
4    Chennai                1

# Binary Encoding
Categories are first converted to integers, then to binary code and each bit becomes a seperate column
reduces number of columns 
better than one hot coding for high cardinality
pip install category_encoders need to be installed

In [17]:
import category_encoders as ce

ModuleNotFoundError: No module named 'category_encoders'

In [18]:
d_b=ce.BinaryEncoder(cols=["City"]).fit_transform(df["City"])
d_b

NameError: name 'ce' is not defined