# import pandas

In [1]:
import pandas as pd
import numpy as np
pd.__version__  # gives the version of pandas

'2.0.3'

# pandas data structues

In [2]:
# Series----one-dimesional coulumn
# DataFrames--- table with rows+cloumns

In [3]:
s=pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [35]:
df=pd.DataFrame({
    "name":["ishu","kallu","aki"],
    "age":[20,23,25]
})
df

    name  age
0   ishu   20
1  kallu   23
2    aki   25

# reading data(csv)

In [36]:
df=pd.read_csv("data.csv")
df

      name  age   city
0  neelima   12    kkd
1  laskhmi   35  vizag
2   akhila   20    ppt
3  kalyani   19    kkd
4     ishu   20    kkd

# writing the data into files

In [37]:
df.to_csv("data.csv",index=False)

# exploring data

In [38]:
df.head()

      name  age   city
0  neelima   12    kkd
1  laskhmi   35  vizag
2   akhila   20    ppt
3  kalyani   19    kkd
4     ishu   20    kkd

In [39]:
df.tail()

      name  age   city
0  neelima   12    kkd
1  laskhmi   35  vizag
2   akhila   20    ppt
3  kalyani   19    kkd
4     ishu   20    kkd

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   city    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [41]:
df["name"][df["city"]=="kkd"]

0    neelima
3    kalyani
4       ishu
Name: name, dtype: object

In [42]:
df[1:3]

      name  age   city
1  laskhmi   35  vizag
2   akhila   20    ppt

In [43]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [44]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [45]:
df.dtypes

name    object
age      int64
city    object
dtype: object

In [46]:
# df.Date-- to display the date it can be also accessed as    --------- df['Date'] -------------

In [47]:
df[['city','age']]

    city  age
0    kkd   12
1  vizag   35
2    ppt   20
3    kkd   19
4    kkd   20

# Missing values

In [50]:
df.isnull()

    name    age   city
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False

In [52]:
df.isnull().sum() # total missin values

name    0
age     0
city    0
dtype: int64

In [55]:
df[df.isnull().any(axis=1)]   # show rows with missing values

Empty DataFrame
Columns: [name, age, city]
Index: []

In [56]:
#df['age']=df['age'].fillna(df['age'].mean()) or df['age']=df['age'].fillna(df['age'].some value)   to fill null value