In [1]:
import pandas as pd 
df=pd.read_csv("data.csv")
df

      name  age   city
0  neelima   12    kkd
1  laskhmi   35  vizag
2   akhila   20    ppt
3  kalyani   19    kkd
4     ishu   20    kkd

In [3]:
df["age"].max()

35

In [4]:
df["age"].min()

12

In [5]:
df["age"].mean()

21.2

In [6]:
df["age"].describe()

count     5.000000
mean     21.200000
std       8.408329
min      12.000000
25%      19.000000
50%      20.000000
75%      20.000000
max      35.000000
Name: age, dtype: float64

In [7]:
import pandas as pd
df[df.age==df.age.max()]

      name  age   city
1  laskhmi   35  vizag

In [8]:
df.count()

name    5
age     5
city    5
dtype: int64

In [9]:
df['city'].nunique()

3

In [10]:
df['city'].unique()

array(['kkd', 'vizag', 'ppt'], dtype=object)

In [11]:
df['city'].value_counts()

city
kkd      3
vizag    1
ppt      1
Name: count, dtype: int64

# string cleaning

In [12]:
import pandas as pd
df= pd.read_csv("data.csv")
df

      name  age   city
0  neelima   12    kkd
1  laskhmi   35  vizag
2   akhila   20    ppt
3  kalyani   19    kkd
4     ishu   20    kkd

In [14]:
df['city']=df['city'].str.upper()
df

      name  age   city
0  neelima   12    KKD
1  laskhmi   35  VIZAG
2   akhila   20    PPT
3  kalyani   19    KKD
4     ishu   20    KKD

In [15]:
df['city']=df['city'].str.lower()
df

      name  age   city
0  neelima   12    kkd
1  laskhmi   35  vizag
2   akhila   20    ppt
3  kalyani   19    kkd
4     ishu   20    kkd

In [16]:
df['name'].str.lower()

0    neelima
1    laskhmi
2     akhila
3    kalyani
4       ishu
Name: name, dtype: object

In [18]:
df['city']=df['city'].str.replace("ppt","RJY")
df

      name  age   city
0  neelima   12    kkd
1  laskhmi   35  vizag
2   akhila   20    RJY
3  kalyani   19    kkd
4     ishu   20    kkd

# Concatenate DataFrames

In [19]:
india=pd.DataFrame({
    "city": ["Mumbai","Agra","Banglore"],
    "temp": [34,23,45]
})
india

       city  temp
0    Mumbai    34
1      Agra    23
2  Banglore    45

In [20]:
us=pd.DataFrame({
    "city": ["Chicago", "Newyork"," Ireland"],
    "temp": [45,23,67]
})
us

       city  temp
0   Chicago    45
1   Newyork    23
2   Ireland    67

In [21]:
df=pd.concat([india,us])
df

       city  temp
0    Mumbai    34
1      Agra    23
2  Banglore    45
0   Chicago    45
1   Newyork    23
2   Ireland    67

In [22]:
df=pd.concat([india,us],ignore_index=True) # it gives line by line ignore index true means it follow ordered index
df

       city  temp
0    Mumbai    34
1      Agra    23
2  Banglore    45
3   Chicago    45
4   Newyork    23
5   Ireland    67

In [23]:
df= pd.concat([india,us],axis=1) # it gives side by side tables
df

       city  temp      city  temp
0    Mumbai    34   Chicago    45
1      Agra    23   Newyork    23
2  Banglore    45   Ireland    67

# Merge dataframes

In [24]:
temp=pd.DataFrame({
    "city":["hyd","vzg","N"],
    "tempt":[34,45,67]
})
temp

  city  tempt
0  hyd     34
1  vzg     45
2    N     67

In [25]:
t=pd.DataFrame({
    "city":["hyd","vzg","vijy"],
    "rainfall":[36,55,77]
})
t

   city  rainfall
0   hyd        36
1   vzg        55
2  vijy        77

In [26]:
df=pd.merge(temp,t,on="city")  #it merges two datas and gives the common columns
df

  city  tempt  rainfall
0  hyd     34        36
1  vzg     45        55

In [27]:
df=pd.merge(temp,t,on="city",how="outer")  #it gives all with null values
df

   city  tempt  rainfall
0   hyd   34.0      36.0
1   vzg   45.0      55.0
2     N   67.0       NaN
3  vijy    NaN      77.0

In [28]:
df.isnull()

    city  tempt  rainfall
0  False  False     False
1  False  False     False
2  False  False      True
3  False   True     False

In [29]:
df.isnull().sum()

city        0
tempt       1
rainfall    1
dtype: int64

In [30]:
df["rainfall"]=df["rainfall"].fillna(df.rainfall.min())
df

   city  tempt  rainfall
0   hyd   34.0      36.0
1   vzg   45.0      55.0
2     N   67.0      36.0
3  vijy    NaN      77.0

In [31]:
df["tempt"]=df["tempt"].fillna(df.tempt.max())
df

   city  tempt  rainfall
0   hyd   34.0      36.0
1   vzg   45.0      55.0
2     N   67.0      36.0
3  vijy   67.0      77.0